steps:
  - id: 'pull image'
    name: 'gcr.io/stargateio/stargate-builder:v1.0.16'
    entrypoint: 'bash'
    args: [ '-c', 'echo pulled builder' ]
  - id: 'fetch_secret'
    waitFor: [ '-' ]
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=stargate-artifactory --format='get(payload.data)' | tr '_-' '/+' | base64 -d > /workspace/ci/custom-settings.xml" ]
  - id: 'fetch codacy secret'
    waitFor: [ '-' ]
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=codacy-project-token --format='get(payload.data)' | tr '_-' '/+' | base64 -d > /workspace/ci/codacy-project-token" ]
  - id: 'init_cache'
    name: 'gcr.io/cloud-builders/gsutil'
    waitFor: [ '-' ]
    args:
      - '-m'
      - '-q'
      - 'rsync'
      - '-r'
      - '-x'
      - '^.*io/stargate.*$'
      - 'gs://${_BUCKET}/cache/.m2'
      - '/cache/.m2'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
  - id: 'dse-6.8'
    waitFor: [ 'fetch_secret', 'init_cache' ]
    name: 'gcr.io/stargateio/stargate-builder:v1.0.16'
    entrypoint: 'bash'
    args: [ 'ci/test.sh' ]
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - 'MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2'
      - 'PERSISTENCE_BACKEND=dse-6.8'
      - 'COMMIT_ID=$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/gsutil'
    waitFor: [ 'dse-6.8' ]
    args:
      - '-m'
      - '-q'
      - 'rsync'
      - '-r'
      - '-x'
      - '^.*io/stargate.*$'
      - '/cache/.m2'
      - 'gs://${_BUCKET}/cache/.m2/'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'

substitutions:
  _BUCKET: 'stargateio-github_cloudbuild'
timeout: 14400s
options:
  machineType: 'N1_HIGHCPU_32'
