steps:
  - id: 'pull image'
    name: 'gcr.io/stargateio/stargate-builder:v1.0.10'
    entrypoint: 'bash'
    args: [ '-c', 'echo pulled builder' ]
  - id: 'fetch_secret'
    waitFor: [ '-' ]
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=stargate-artifactory --format='get(payload.data)' | tr '_-' '/+' | base64 -d > /workspace/ci/custom-settings.xml" ]
  - id: 'fetch codacy secret'
    waitFor: [ '-' ]
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=codacy-project-token --format='get(payload.data)' | tr '_-' '/+' | base64 -d > /workspace/ci/codacy-project-token" ]
  - id: 'init_cache'
    name: 'gcr.io/cloud-builders/gsutil'
    waitFor: [ '-' ]
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-x'
      - '^.*io/stargate.*$'
      - 'gs://${_BUCKET}/cache/.m2'
      - '/cache/.m2'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
  - id: 'build'
    name: 'maven:3-jdk-8'
    waitFor: [ 'fetch_secret', 'init_cache' ]
    entrypoint: mvn
    args: [ '-B','install', '--settings', 'ci/custom-settings.xml', '--file', 'pom.xml', '-DskipITs',
            '-Dmaven.javadoc.skip=true', '-Pdse', '-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
    ]
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - 'MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2'
  - name: 'gcr.io/cloud-builders/gsutil'
    waitFor: [ 'build' ]
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-x'
      - '^.*io/stargate.*$'
      - '/cache/.m2'
      - 'gs://${_BUCKET}/cache/.m2/'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'

substitutions:
  _BUCKET: 'stargateio-github_cloudbuild'
timeout: 14400s
options:
  machineType: 'N1_HIGHCPU_8'
