steps:
  - id: 'fetch_secret'
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=stargate-artifactory --format='get(payload.data)' | tr '_-' '/+' | base64 -d > /workspace/ci/custom-settings.xml" ]
  #  - id: 'build'
  #    waitFor: [ 'fetch_secret' ]
  #    name: 'ubuntu:bionic'
  #    entrypoint: 'bash'
  #    args: [ 'ci/build.sh' ]
  - id: 'build'
    waitFor: [ 'fetch_secret' ]
    name: 'maven:3-jdk-8'
    entrypoint: mvn
    args: [ '-B','install', '--settings', 'ci/custom-settings.xml', '--file', 'pom.xml', '-DskipITs',
            '-Dmaven.javadoc.skip=true', '-Pdse', '-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
    ]
  - id: 'cassandra-3.11'
    waitFor: [ 'build' ]
    name: 'ubuntu:bionic'
    entrypoint: 'bash'
    args: [ 'ci/test.sh' ]
    env:
      - 'PERSISTENCE_BACKEND=cassandra-3.11'
  - id: 'cassandra-4.0'
    waitFor: [ 'build' ]
    name: 'ubuntu:bionic'
    entrypoint: 'bash'
    args: [ 'ci/test.sh' ]
    env:
      - 'PERSISTENCE_BACKEND=cassandra-4.0'
  - id: 'dse-6.8'
    waitFor: [ 'build' ]
    name: 'ubuntu:bionic'
    entrypoint: 'bash'
    args: [ 'ci/test.sh' ]
    env:
      - 'PERSISTENCE_BACKEND=dse-6.8'
timeout: 10800s
options:
  machineType: 'N1_HIGHCPU_32'