#!/bin/bash
set -e

cleanup() {
    # kill all processes whose parent is this process
    pkill -9 -P $$
}

for sig in INT QUIT HUP TERM EXIT; do
  trap cleanup "$sig"
done

cd -P -- "$(dirname -- "$0")" # switch to this dir
echo $PWD

if [ -z $BRIDGE_TOKEN ]; then
  export BRIDGE_TOKEN=mockAdminToken
fi

# start REST API service
./starctl-service-rest &

# pass along same arguments to script to start coordinator
./starctl-coordinator "$@" --bridge-token="$BRIDGE_TOKEN" &

wait

