#!/bin/bash
set -e

cleanup() {
    # kill all processes whose parent is this process
    pkill -9 -P $$
}

for sig in INT QUIT HUP TERM EXIT; do
  trap cleanup "$sig"
done

cd -P -- "$(dirname -- "$0")" # switch to this dir
echo $PWD

# start REST API service
./starctl-service-rest &

./starctl-service-graphql &

# pass along same arguments to script to start coordinator
./starctl-coordinator "$@" &

wait

