#!/bin/bash
set -e

if type -p java >/dev/null; then
    _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    _java="$JAVA_HOME/bin/java"
else
    echo "\$JAVA_HOME not found"
    exit 1
fi

if [[ "$_java" ]]; then
    jvmver=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
    JVM_VERSION=${jvmver%_*}
    JVM_PATCH_VERSION=${jvmver#*_}

    if [ "$JVM_VERSION" \< "1.8" ] ; then
        echo "Stargate requires Java 8u40 or later."
        exit 1
    fi

    if [ "$JVM_VERSION" \< "1.8" ] && [ "$JVM_PATCH_VERSION" -lt 40 ] ; then
        echo "Stargate requires Java 8u40 or later."
        exit 1
    fi
fi

# If STARGATE_HOME wasn't specified in the environment, then search for one...
if [ "x$STARGATE_HOME" == "x" ]; then
    STARGATE_HOME="`dirname "$0"`/stargate-lib"
    if [[ ! -d $STARGATE_HOME ]]; then
      echo "STARGATE_HOME not found"
      exit 2
    fi
else
    if [[ ! -d $STARGATE_HOME ]]; then
      echo "STARGATE_HOME: '$STARGATE_HOME' is not a directory"
      exit 2
    fi
fi

eval declare -a JAVA_OPTS=("$GRAPHQL_JAVA_OPTS")

if [ ! "x$STARGATE_BRIDGE_HOST" == "x" ]; then
  JAVA_OPTS+=(-Ddw.stargate.bridge.host="$STARGATE_BRIDGE_HOST")
else
  JAVA_OPTS+=(-Ddw.stargate.bridge.host=localhost)
fi

if [ ! "x$STARGATE_BRIDGE_PORT" == "x" ]; then
  JAVA_OPTS+=(-Ddw.stargate.bridge.port="$STARGATE_BRIDGE_PORT")
else
  JAVA_OPTS+=(-Ddw.stargate.bridge.port=8091)
fi

if [ ! "x$STARGATE_GRAPHQL_PORT" == "x" ]; then
  JAVA_OPTS+=(-Ddw.server.connector.port="$STARGATE_GRAPHQL_PORT")
else
  JAVA_OPTS+=(-Ddw.server.connector.port=9080)
fi

echo "Starting GraphQL API Service"

declare -a CMD=(java -server)
CMD+=("${JAVA_OPTS[@]}")
CMD+=(-jar $STARGATE_HOME/graphql/sgv2-graphqlapi*.jar)
echo "Running" "${CMD[@]}"
exec "${CMD[@]}"
