{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stargate-grpc-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - http:
      paths:
      - backend:
          service:
            name: stargate-grpc
            port:
              number: 8090
        path: /api/grpc(/|$)(.*)
        pathType: Prefix
{{ end }}
