apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: stargate-auth
  name: stargate-auth
spec:
  ports:
  - name: stargate-auth
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: coordinator
  type: ClusterIP
status:
  loadBalancer: {}
