{{ if .Values.restapi.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: stargate-restapi
  name: stargate-restapi
spec:
  ports:
  - name: stargate-restapi
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: stargate-restapi
  type: ClusterIP
status:
  loadBalancer: {}
{{ end }}
