apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: stargate-grpc
  name: stargate-grpc
spec:
  ports:
  - name: stargate-grpc
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: coordinator
  type: ClusterIP
status:
  loadBalancer: {}
