apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: stargate-bridge
  name: stargate-bridge
spec:
  ports:
  - name: stargate-bridge
    port: 8091
    protocol: TCP
    targetPort: 8091
  selector:
    app: coordinator
  type: ClusterIP
status:
  loadBalancer: {}
