{{ if .Values.ingress.enabled }}
{{ if .Values.graphqlapi.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stargate-restapi-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - http:
      paths:
      - backend:
          service:
            name: stargate-graphqlapi
            port:
              number: 8080
        path: /api/graphql(/|$)(.*)
        pathType: Prefix
{{ end }}
{{ end }}
