{{ if .Values.graphqlapi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stargate-graphqlapi
  labels:
    app: stargate-graphqlapi
spec:
  replicas: {{ .Values.graphqlapi.replicaCount }}
  selector:
    matchLabels:
      app: stargate-graphqlapi
  template:
    metadata:
      labels:
        app: stargate-graphqlapi
    spec:
      containers:
      - name: graphqlapi
        image: "stargateio/graphqlapi:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        #readinessProbe:
        #  httpGet:
        #    path: /q/health/ready
        #    port: 8080
        #  timeoutSeconds: 20
        #  initialDelaySeconds: 80
        #livenessProbe:
        #  httpGet:
        #    path: /q/health/live
        #    port: 8080
        #  initialDelaySeconds: 80
        #  timeoutSeconds: 20
        resources:
          limits:
            cpu: {{ mul 4 (.Values.graphqlapi.cpu | default 500) }}m
            memory: {{add 500 (.Values.graphqlapi.memory | default 512)}}Mi
          requests:
            cpu: {{ mul 4 (.Values.graphqlapi.cpu | default 200) }}m
            memory: {{add 500 (.Values.graphqlapi.memory | default 512)}}Mi
        env:
        - name: QUARKUS_GRPC_CLIENTS_BRIDGE_HOST
          value: "stargate-coordinator"
        - name: IO_STARGATE_SGV2_API_COMMON_PROPERTIES_DATASTORE_CONFIGURATION_DATASTOREPROPERTIESCONFIGURATION_FETCHSUPPORTEDFEATURES_RETRY_MAXRETRIES
          value: "50"
        - name: IO_STARGATE_SGV2_API_COMMON_PROPERTIES_DATASTORE_CONFIGURATION_DATASTOREPROPERTIESCONFIGURATION_FETCHSUPPORTEDFEATURES_RETRY_MAXDURATION
          value: "300"
        - name: IO_STARGATE_SGV2_API_COMMON_PROPERTIES_DATASTORE_CONFIGURATION_DATASTOREPROPERTIESCONFIGURATION_FETCHSUPPORTEDFEATURES_RETRY_DELAY
          value: "10"
{{ end }}
