{{ if .Values.graphqlapi.enabled }}

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: stargate-graphqlapi
  name: stargate-graphqlapi
spec:
  ports:
  - name: stargate-graphqlapi
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: stargate-graphqlapi
  type: ClusterIP
status:
  loadBalancer: {}
{{ end }}
