apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: stargate-coordinator
  name: stargate-coordinator
spec:
  ports:
  - name: stargate-coordinator
    port: 8091
    protocol: TCP
    targetPort: 8091
  selector:
    app: coordinator
  type: ClusterIP
status:
  loadBalancer: {}
