apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: stargate-cql
  name: stargate-cql
spec:
  ports:
  - name: stargate-cql
    port: 9042
    protocol: TCP
    targetPort: 9042
  selector:
    app: coordinator
  type: ClusterIP
status:
  loadBalancer: {}
