server:
  type: rest-api
  applicationContextPath: /
  connector:
    type: http
    # 28-Sep-2022, tatu: Port number for in-Coordinator REST API (and Documents API)
    #    remains the same as in SGv1, for backwards compatibility reasons
    port: 8082
  requestLog:
    type: external
logging:
    type: external

