server:
  type: sgv2-restapi
  applicationContextPath: /
  connector:
    type: http
    # 11-Feb-2022, tatu: For Stargate V1, REST+Docs were both on port 8082, but for Stargate V2
    #    will separate the two and the "new" REST API inherits 8082
    port: 8082
  requestLog:
    type: external
stargate:
  bridge:
    host: localhost
    port: 8091
    useTls: false
logging:
    type: external

