server:
  type: sgv2-restapi
  applicationContextPath: /
  connector:
    type: http
    # 11-Feb-2022, tatu: This implementation will be removed soon, but until then
    #    has to expose port OTHER than 8082 for ITs to work
    port: 8083
  requestLog:
    type: external
stargate:
  bridge:
    host: localhost
    port: 8091
    useTls: false
logging:
    type: external

