server:
  type: sgv2-restapi
  applicationContextPath: /
  connector:
    type: http
    # 28-Sep-2022, tatu: This is the intermediate SGv2 REST API implementation built
    #    (like SGv1/REST) on DropWizard. For ITs it must NOT run on 8082 to avoid conflict
    #    We hope to rm this implementation ASAP but until then let's expose via 8083?
    port: 8083
  requestLog:
    type: external
stargate:
  bridge:
    host: localhost
    port: 8091
    useTls: false
logging:
    type: external

