# Default values for stargate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: "docker.io"
  repository311: "stargateio/coordinator-3_11" 
  repository40: "stargateio/coordinator-4_0" 
  repositoryDse68: "stargateio/coordinator-dse-68" 
  tag: "v2"

cassandra:
  clusterName: "cassandra"
  dcName: "datacenter1"
  rack: "rack1"
  seed: "my-release-cassandra-headless" 
  isDse: null
  clusterVersion: "4.0"
  enableCqlAuth: true

cpuReqMillicores: 1000
heapMB: 1024

restapi:
  image:
    repository: "stargateio/restapi"
  enabled: true
  replicaCount: 1
  cpu: 500
  memory: 512

docsapi:
  image:
    repository: "stargateio/docsapi"
  enabled: true
  replicaCount: 1
  cpu: 500
  memory: 512

graphqlapi:
  image:
    repository: "stargateio/graphqlapi"
  enabled: true
  replicaCount: 1
  cpu: 500
  memory: 512

