# Default values for stargate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Bridge relication count. This is also the replication for CQL, Auth and GRPC end points.
replicaCount: 1

# Coordinator or bridge registry and image
image:
  registry: "docker.io"
  repository311: "stargateio/coordinator-3_11" 
  repository40: "stargateio/coordinator-4_0" 
  repositoryDse68: "stargateio/coordinator-dse-68" 
  tag: "v2"

# Storage cassandra details
cassandra:
  clusterName: "cassandra"
  dcName: "datacenter1"
  rack: "rack1"
  seed: "my-release-cassandra-headless.default.svc.cluster.local" 
  isDse: null
  clusterVersion: "4.0"
  enableCqlAuth: true

# CPU and Memory request and limit for cordinator
cpuReqMillicores: 2000
heapMB: 2048

# Rest service image - don't change it. Can be disabled with enabled flag set to false. replicaCount for number for replicas to start with. CPU and memory are both request and limits
restapi:
  image:
    repository: "stargateio/restapi"
  enabled: true
  replicaCount: 1
  cpu: 2000
  memory: 2048


# Document service image - don't change it. Can be disabled with enabled flag set to false. replicaCount for number for replicas to start with. CPU and memory are both request and limits
docsapi:
  image:
    repository: "stargateio/docsapi"
  enabled: true
  replicaCount: 1
  cpu: 2000
  memory: 2048


# Graphql service image - don't change it. Can be disabled with enabled flag set to false. replicaCount for number for replicas to start with. CPU and memory are both request and limits
graphqlapi:
  image:
    repository: "stargateio/graphqlapi"
  enabled: true
  replicaCount: 1
  cpu: 2000
  memory: 2048

# HorizontalPodAutoscaler for coordinator and all services. This needs metrics server installed (kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml) in the cluster. 
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
