name: Complete v2 Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "v2.0.0"
      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Maven
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>artifactory-snapshots</id>
                <username>${ARTIFACTORY_USERNAME}</username>
                <password>${ARTIFACTORY_PASSWORD}</password>
              </server>
              <server>
                <id>artifactory-releases</id>
                <username>${ARTIFACTORY_USERNAME}</username>
                <password>${ARTIFACTORY_PASSWORD}</password>
             </server>
           </servers>
          </settings>
          EOF
      - name: Build with Maven
        run: |
          mvn versions:set -DremoveSnapshot versions:commit
          mvn -P dse -q -ff clean package -DskipTests
      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build and push
        run: |
          ./build_docker_images.sh -p -t ${{ steps.vars.outputs.tag }}
      - name: Update version numbers for next release
        run: |
          mvn -B release:update-versions -DautoVersionSubmodules=true versions:commit -Pdse && \
          mvn xml-format:xml-format fmt:format -Pdse
      - name: Rev Version
        if: success()
        uses: peter-evans/create-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: "Bumping version for next v2 release"
          title: "Bumping version for next v2 release"
          branch-suffix: "short-commit-hash"
          base: "v2.0.0"
          labels: "stargate-v2"
