# @author Ivan Senic
name: Merge main/v1

# runs on
# * stargate v1 release event
# * manual trigger
on:
  repository_dispatch:
    types: [ stargate-v1-release ]
  workflow_dispatch:

jobs:

  merge:
    name: Merge branches
    runs-on: ubuntu-latest

    steps:

      # always checkout main, but fetch complete history
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      # run merge without a commit (will be added in final step)
      - name: Run git merge
        run: git merge --no-commit -s ours origin/v1

      # commit and create pr
      - name: Create pull-request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Merging branch v1 into main
          branch: create-pull-request/merge-main-v1
          branch-suffix: short-commit-hash
          base: main
          labels: stargate-v2
          title: Merging branch v1 into main
          body: |
            Automated changes that try to merge v1 into main.
            
            **IMPORTANT: When merging please use the fast-forward merge and avoid GitHub merge buttons.**
