name: Find port user

on:
  workflow_dispatch:

jobs:

  check-port-user:
    name: Who's using that port
    runs-on: ubuntu-latest
    steps:
      - name: lsof
        run: |
          sudo lsof -iTCP -n -P | sort -k1